name: Build and test the app

on:
  push:
    branches: [ "main", "VelkoBranch" ]
  pull_request:
    branches: [ "main", "VelkoBranch" ]
  #schedule:
  #  - cron: '*/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
